# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test <- function(points, query, n_samples = 100L, depth = 5L) {
    .Call(`_quadtree_test`, points, query, n_samples, depth)
}

