# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test <- function(points, query, depth = 5L) {
    .Call(`_quadtree_test`, points, query, depth)
}

test_range <- function(points, query, depth = 5L) {
    .Call(`_quadtree_test_range`, points, query, depth)
}

